name: cine_explorer
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3  
  http: ^1.1.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: BebasNeueBold
      fonts:
        - asset: assets/fonts/BebasNeue Bold.otf
    - family: BebasNeueRegular
      fonts:
        - asset: assets/fonts/BebasNeue Regular.otf  
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf    
